[metadata]
name = xco2qc
version = 0.0.1
author = 'John Evans'
author_email = "John Evans" <jevansuw@uw.edu>
license = 'MIT'
long_description_content_type = text/markdown
long_description = 
    XCO2 processing pipeline Tools for PMEL ocean carbon group
classifiers = 
    Programming Languages :: Python
    Programming Languages :: Python :: 3.9
    Programming Languages :: Python :: 3.10
    Programming Languages :: Python :: Implementation :: CPython
    License :: OSI Approved :: MIT License
    Intended Audience :: OS Independent
    Topic :: Scientific/Engineering

[options]
include_package_data = True

[options.entry_points]
console_scripts =
    xco2-import = xco2qc.commandline:import_mapco2
    xco2-reduce = xco2qc.commandline:mapco2_reduce
    xco2-initial-summmary = xco2qc.commandline:initial_summary
    xco2-pre = xco2qc.commandline:calculate_pre_xco2
    xco2-post = xco2qc.commandline:calculate_post_xco2
    xco2-qc = xco2qc.commandline:qc_xco2
    xco2-merge = xco2qc.commandline:merge
    xco2-adjustments = xco2qc.commandline:adjustments
    xco2-apply-metadata-conventions = xco2qc.commandline:apply_metadata_conventions
    xco2-gen-socat = xco2qc.commandline:generate_socat_xml
    xco2-socat-qc = xco2qc.commandline:calculate_socat_qc
    xco2-compare-mbl = xco2qc.commandline:compare_with_mbl
    xco2-trim = xco2qc.commandline:trim
    xco2-nc2csv = xco2qc.commandline:nc2csv

[options.package_data]
xco2qc = 
    core/climatology/chl/data/*.xlsx
    core/climatology/o2/data/*.xlsx
    core/data/*.xlsx
    core/data/*.yml
    core/data/vardefs/config/*.yml

[flake8]
exclude=xco2qc/science_algorithms/o2/*.py,xco2qc/Outlier_Detector.py
